version: "3"

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: always
    networks:
      - traefik
    ports:
      - 2375
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ddns:
    image: qmcgaw/ddns-updater:latest
    container_name: ddns
    ports:
      - 8000:8000
    volumes:
      - ./ddns:/updater/data
    restart: always

  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis/data:/data

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8888:8080

  traefik:
    image: traefik:v2.9.5
    container_name: traefik
    restart: always
    networks:
      - default
      - traefik
    depends_on:
      - docker-socket-proxy
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://docker-socket-proxy:2375"
      - "--providers.docker.network=traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=acme.home.100terres.com@100terres.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 9999:9999
    volumes:
      - ./letsencrypt:/letsencrypt

networks:
  default:
    name: web
  traefik:
    name: traefik

secrets:
  postgres-password:
    file: ./postgres/secrets/postgres-password.txt
