events {}

http {
    upstream widgets {
        include /etc/nginx/active_service.conf;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://widgets;
        }
    }
}
