# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json

services:
  widgets-server:
    image: core.registry:5000/100terres/widgets:latest
    container_name: widgets-server
    restart: unless-stopped
    expose:
      - 80
    networks:
      - gateway-widgets-resource
    labels:
      - wud.registry=core
      - wud.watcher.fast.watch=true
      - wud.tag.include=latest
      - wud.watch.digest=true
networks:
  gateway-widgets-resource:
    name: gateway-widgets-resource
    external: true
