# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json

services:
  widgets-proxy:
    image: nginx:alpine:latest
    container_name: widgets-proxy
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - widgets-default
      - gateway-widgets-resource
  widgets-server-a:
    image: core.registry:5000/100terres/widgets:latest
    container_name: widgets-server-a
    restart: unless-stopped
    expose:
      - 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - widgets-default
    environment:
      - SERVER_HEALTH=true
  widgets-server-b:
    image: core.registry:5000/100terres/widgets:latest
    container_name: widgets-server-b
    restart: unless-stopped
    expose:
      - 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - widgets-default
    environment:
      - SERVER_HEALTH=true
networks:
  widgets-default:
    name: widgets-default
  gateway-widgets-resource:
    name: gateway-widgets-resource
    external: true
