events {}

http {
    upstream 100terres-com {
        include /etc/nginx/active_service.conf;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://100terres-com;
        }
    }
}
